### ISSUE TITLE
Formatting looks really weird on mobile currently

### ISSUE THREAD

**Issue by carschandler** [NixOS/nix-pills#231] opened 2024-03-15 15:12 UTC
I just opened the site a few weeks ago and everything looked fine but today on mobile I’m getting this look:
![image](https://github.com/NixOS/nix-pills/assets/92899389/e17f9d16-0ff4-42a1-aece-eb628abce7c8)

Not sure if it's occurring on desktop too.

**Comment by olafklingt** [comment] 2024-03-15 18:49
I think this is a effect the recent website update could be interpreted as a duplicate of https://github.com/NixOS/nixos-homepage/issues/1251

**Comment by carschandler** [comment] 2024-03-15 18:59
That is definitely the case! I’ll close in favor of that issue.

**Comment by infinisil** [comment] 2024-03-16 04:39
Unfortunately the PR fixing it for Nixpkgs/NixOS won't fix it for the Nix Pills :/

So I think we should still leave this open for now

**Comment by henrik-ch** [comment] 2024-04-16 08:25
It doesn't look like this issue still exists as far as I can see. Can we close it?

![image](https://github.com/NixOS/nix-pills/assets/569510/a92d091e-6948-49a5-ae2d-ca928f6a2b34)

**Closed** 2024-04-16 08:37 UTC
